w6d3-rails-mvc-intro/jungle/config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
  end

end

w6d3-rails-mvc-intro/jungle/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

end

w6d3-rails-mvc-intro/jungle/app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

w6d3-rails-mvc-intro/jungle/app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

w6d3-rails-mvc-intro/jungle/app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true

end

w6d3-rails-mvc-intro/jungle/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
  end
end

w6d3-rails-mvc-intro/jungle/app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

w6d3-rails-mvc-intro/jungle/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def cart
    # value = cookies[:cart] || JSON.generate({})
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end

end

w6d3-rails-mvc-intro/jungle/app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

  def add_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 0 }
    item["quantity"] += 1
    cart[product_id] = item
    update_cart cart

    redirect_to :back
  end

  def remove_item
    product_id = params[:product_id].to_s

    item = cart[product_id] || { "quantity" => 1 }
    item["quantity"] -= 1
    cart[product_id] = item
    cart.delete(product_id) if item["quantity"] < 1
    update_cart cart

    redirect_to :back
  end

end

w6d3-rails-mvc-intro/jungle/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

w6d3-rails-mvc-intro/jungle/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, error: order.errors.full_messages.first
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, error: e.message
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_total, # in cents
      description: "Khurram Virani's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_total,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )
    cart.each do |product_id, details|
      if product = Product.find_by(id: product_id)
        quantity = details['quantity'].to_i
        order.line_items.new(
          product: product,
          quantity: quantity,
          item_price: product.price,
          total_price: product.price * quantity
        )
      end
    end
    order.save!
    order
  end

  # returns total in cents not dollars (stripe uses cents as well)
  def cart_total
    total = 0
    cart.each do |product_id, details|
      if p = Product.find_by(id: product_id)
        total += p.price_cents * details['quantity'].to_i
      end
    end
    total
  end

end

w6d3-rails-mvc-intro/jungle/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

w6d3-rails-mvc-intro/jungle/app/helpers/application_helper.rb
module ApplicationHelper
end

w6d3-rails-mvc-intro/jungle/app/views/admin/dashboard/show.html.erb
<h1>Admin::Dashboard#show</h1>
<p>Find me in app/views/admin/dashboard/show.html.erb</p>

w6d3-rails-mvc-intro/jungle/app/views/admin/products/_product.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= product.category.name %>
  </td>
  <td>
    <%= product.price %>
  </td>
  <td>
    <%= product.quantity %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, product], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>
</tr>

w6d3-rails-mvc-intro/jungle/app/views/admin/products/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Products</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Qty Remaining</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>

  </div>

</section>

w6d3-rails-mvc-intro/jungle/app/views/admin/products/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Product</h1>
  </header>

  <div class="well">
    <%= link_to 'All Products', [:admin, :products], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @product] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.select :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name), { include_blank: true }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :quantity %>
          <%= form.number_field :quantity, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :price %>
          <%= form.text_field :price, class: 'form-control' %>
        </div>



        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image %>
        </div>

        <%= form.submit 'Create Product', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

w6d3-rails-mvc-intro/jungle/app/views/carts/_item.html.erb
<% quantity = details['quantity'].to_i %>

<% if product = Product.find_by(id: product_id) %>
  <% item_total = product.price * quantity %>
  <% @cart_total += item_total %>

  <tr>
    <td>
      <%= image_tag product.image.tiny %>
    </td>
    <td>
      <h4><%= product.name %></h4>
      <br>
      <p><%= product.description %></p>
    </td>
    <td>
      <%= product.price %>
    </td>
    <td>
      <%= link_to remove_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-danger', method: :delete do %>
        -
      <% end %>
      <%= quantity %>
      <%= link_to add_item_cart_path(product_id: product_id), class: 'btn btn-xs btn-success', method: :put do %>
        +
      <% end %>
    </td>
    <td>
      <%= item_total %>
    </td>
  </tr>
<% end %>

w6d3-rails-mvc-intro/jungle/app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>

  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_total = 0 %>
        <% cart.each do |product_id, details| %>
          <%= render 'item', product_id: product_id, details: details %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            <%= @cart_total %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= @cart_total * 100 %>"
          data-name="Jungle"
          data-description="Khurram Virani's Jungle Order"
          data-locale="auto"
          data-email="kvirani@gmail.com"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>

</section>

w6d3-rails-mvc-intro/jungle/app/views/orders/show.html.erb
<section class="orders-show">

  <header class="page-header">
    <h1>Order #<%= @order.id %></h1>
  </header>

  <div class="order-summary jumbotron">
    <h4>Thank you for your order!</h4>
  </div>

  <%= link_to "Continue Shopping", root_path, class: 'btn btn-lg btn-primary' %>

</section>

w6d3-rails-mvc-intro/jungle/app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
      <%= image_tag product.image.thumb, alt: product.name %>
      <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <%= link_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary', method: :put do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
</article>

w6d3-rails-mvc-intro/jungle/app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

w6d3-rails-mvc-intro/jungle/app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd><%= @product.price %></dd>
        </dl>
      </div>
    </div>

  </article>

</section>